app:
  port: 3000
  paging:
    maxItemPerPage: 20
  scan:
    localRepoPath: /tmp/cscanner/git-repo/
    workerCount: 5
    wordDelimiter: ' ' # Single character only, represent a byte.
    findingRule:
      - type: public_key
        match: prefix
        ruleID: G402
        description: Exposed sensitive information.
        severity: HIGH
      - type: private_key
        match: prefix
        ruleID: G402
        description: Exposed sensitive information.
        severity: HIGH
    ignore: .git,.vscode,.idea

postgres:
  host: localhost
  port: 5432
  database: db
  username: root
  password: password
  connectionTimeout: 60000
  isPrintLog: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  publishTimeout: 5000
  queue:
    name: scanner
