app:
  port: 3000
  paging:
    maxItemPerPage: 50
  scan:
    localRepoPath: /tmp/cscanner/git-repo/
    workerCount: 5
    wordDelimiter: ' ' # Single byte character only
    ignore: .git,.vscode,.idea # Comma delimited

postgres:
  connectionTimeout: 60000
  isPrintLog: true

rabbitmq:
  publishTimeout: 5000
  queue:
    name: scanner
