app:
  port: 3000
  paging:
    maxItemPerPage: 50
  scan:
    localRepoPath: /tmp/cscanner/git-repo/
    workerCount: 5
    wordDelimiter: ' ' # Single character only, represent a byte.
    findingRule:
      - type: public_key
        match: prefix
        ruleID: G402
        description: Exposed sensitive information.
        severity: HIGH
      - type: private_key
        match: prefix
        ruleID: G402
        description: Exposed sensitive information.
        severity: HIGH
    ignore: .git,.vscode,.idea

postgres:
  connectionTimeout: 60000
  isPrintLog: true

rabbitmq:
  publishTimeout: 5000
  queue:
    name: scanner
